[package]
name = "trash"
version = "0.1.0"
authors = ["Sayan751 <sayan751@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
email-address-parser = { path = "../rust-lib", version = "0.1.0" }