[package]
name = "email-address-parser"
version = "0.1.0"
authors = ["Sayan Pal <spal@netatwork.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "^2.1.3"
pest_derive = "^2.1.0"

[build-dependencies]
quick-xml = "^0.18.1"