[package]
name = "email-address-parser"
version = "0.2.0-rc8"
authors = ["Sayan751"]
edition = "2018"
description = "An RFC 5322 compliant email address parser."
repository = "https://github.com/Sayan751/email-address-parser"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "email_address_parser"
crate-type = ["lib", "cdylib"]

[dependencies]
pest = "^2.1.3"
pest_derive = "^2.1.0"
wasm-bindgen = "^0.2.67"

[build-dependencies]
quick-xml = "^0.18.1"

[dev-dependencies]
wasm-bindgen-test = "^0.3.17"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-mutable-globals"]