name: Rust

defaults:
  run:
    working-directory: rust-lib

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Rust
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: test WASM
      run: wasm-pack test --node --verbose
