name: Rust

defaults:
  run:
    working-directory: rust-lib

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    
    - name: Build Rust
      run: cargo build --verbose --release
    
    - name: Run tests
      run: cargo test --verbose
    
    - name: Build docs
      run: cargo doc --no-deps
    
    - name: test WASM Chrome
      run: wasm-pack test --headless --chrome
    
    - name: test WASM Firefox
      run: wasm-pack test --headless --firefox
    
    - name: build WASM bundler
      run: wasm-pack build --out-dir ../npm-pkg/dist/bundler
    
    - name: build WASM cjs
      run: wasm-pack build --target nodejs --out-dir ../npm-pkg/dist/cjs
    
    - name: cleanup dist
      run: rm ../npm-pkg/dist/bundler/.gitignore ../npm-pkg/dist/bundler/email_address_parser.d.ts ../npm-pkg/dist/bundler/LICENSE ../npm-pkg/dist/bundler/package.json  ../npm-pkg/dist/bundler/README.md ../npm-pkg/dist/cjs/.gitignore ../npm-pkg/dist/cjs/email_address_parser.d.ts ../npm-pkg/dist/cjs/LICENSE ../npm-pkg/dist/cjs/package.json  ../npm-pkg/dist/cjs/README.md

    - name: test npm package
      run: npm test --prefix ../npm-pkg
