name: Rust

defaults:
  run:
    working-directory: rust-lib

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Build Rust
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
    - name: Build docs
      run: cargo doc --no-deps
    - name: test WASM Chrome
      run: wasm-pack test --headless --chrome
    - name: test WASM Firefox
      run: wasm-pack test --headless --firefox
