name: Rust

defaults:
  run:
    working-directory: rust-lib

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-out:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

  install-wasm-bindgen:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Install
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

  build-rust:

    runs-on: ubuntu-latest
    
    steps:
    - name: Install
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Build Rust
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
    - name: Build docs
      run: cargo doc --no-deps

    needs: [check-out]
  
  build-wasm:

    runs-on: ubuntu-latest
    
    steps:
    - name: test WASM
      run: wasm-pack test --node

    needs: [check-out, install-wasm-bindgen]
